### PR TITLE
add faculty Model

### PR DESCRIPTION
**Pull request by SaiChandra2896**
add faculty model

### CODE REVIEW

**Comment by SaiChandra2896** [comment]
@aloks98 please review above PR and can u please add 'hacktoberfest' label, thank you

**Comment by SaiChandra2896** [comment]
added marks model

**Comment by aloks98** [comment]
Good job @SaiChandra2896 and thanks!

**Review by aloks98 — APPROVED** [review]

**Comment by SaiChandra2896** [comment]
@aloks98 thank you so much

**Pull request merged**
